baseURL = "https://www.juev.org/"
languageCode = "ru-RU"
title = "Denis Evsyukov"
images = "https://www.juev.org/juev.png"
description = "My thoughts and findings"

copyright = "This work is licensed under a MIT License."

summarylength = 10

rssLimit = 5

pygmentsOptions = ["noclasses"]
pygmentsCodeFences = true

enableEmoji = true

[author]
name = "Denis Evsyukov"

[frontmatter]
date = [":filename", ":default"]

[permalinks]
posts = "/:year/:month/:day/:slug/"
# pages = "/:slug/"

[taxonomies]
tag = "tags"

[outputs]
home = ["HTML", "RSS"]
page = ["HTML"]

[mediaTypes]
[mediaTypes."application/xml"]
suffixes = ["xml"]

[outputFormats]

[outputFormats.Sitemap]
mediaType = "application/xml"

[outputFormats.RSS]
baseName = "atom"

[params]
ogimage = "https://www.juev.org/juev.png"
footer = '''Except where otherwise noted, content on this site is licensed under
    a <a href="http://creativecommons.org/licenses/by/4.0/" rel="license">
    Creative Commons Attribution 4.0 International License</a>.'''
rss = '''To subscribe to this RSS feed, copy its address and paste it into your
    favorite feed reader.'''
description = "My thoughts and findings"

[params.social]
github		= "juev"
twitter		= "juev"
twitter_domain	= "www.juev.org" # This domain shows in twitter cards as "View on `twitter_domain`"

[params.authors]
[params.authors.Denis]
name			= "Denis Evsyukov"
thumbnail		= "https://www.juev.org/juev.png"
images		= []
bio			= "John Connor is the son of Sarah Connor and Kyle Reese, and the leader of the worldwide human resistance..."
email			= "denis@evsyukov.org"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "monokailight"
    tabWidth = 4

[deployment]

[[deployment.targets]]
name = "www.juev.org"
URL = "s3://www.juev.org?region=eu-west-2"

[[deployment.matchers]]
# Cache static assets for 20 years.
pattern = "^.+\\.(js|css|ttf|ico)$"
cacheControl = "max-age=630720000, no-transform, public"
gzip = true

[[deployment.matchers]]
# Cache static assets for 20 years.
pattern = "^.+\\.(png|jpg|gif|svg)$"
cacheControl = "max-age=630720000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
cacheControl = "public, no-cache, must-revalidate"
gzip = true

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
cacheControl = "public, no-cache, must-revalidate"
contentType = "application/xml"
gzip = true