name: Deploy site

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Build
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.89.2"
          extended: true
      - name: Build
        run: hugo --gc && rm -rf public/pages
      # Deploy
      - name: Install s3deploy
        run: |
          S3DEPLOY_DOWNLOAD=s3deploy_${S3DEPLOY_VERSION}_Linux-64bit.tar.gz
          set -x
          set -e
          wget https://github.com/bep/s3deploy/releases/download/v${S3DEPLOY_VERSION}/${S3DEPLOY_DOWNLOAD}
          tar xvzf ${S3DEPLOY_DOWNLOAD} s3deploy
        env:
          S3DEPLOY_VERSION: 2.5.1
      - name: Deploy to S3
        run: ./s3deploy -bucket www.juev.org -acl='public-read' -region eu-west-2 -max-delete -1 -source public/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # Purge cache
      - uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
